all:
	gcc main.c packetManage.c -o a.out -lpcap -v  && ./a.out 
d:
	gcc main.c packetManage.c -o a.out -I/System/Volumes/Data/sgoinfre/goinfre/Perso/$USER/homebrew/Cellar/libnet/1.2/include -lpcap -v -Wall -g && ./a.out 
